from __future__ import annotations

COLUMN_CANDIDATES = {
    "employee_id": [
        "legajo",
        "employee id",
        "employeeid",
        "emp id",
        "user id",
        "userid",
        "id empleado",
        "person id",
        "staff id",
        "codigo",
        "no.",
        "card no",
    ],
    "employee_name": [
        "nombre",
        "employee name",
        "name",
        "apellido y nombre",
        "person name",
        "staff name",
        "empleado",
        "user name",
    ],
    "punch_datetime": [
        "fecha y hora",
        "datetime",
        "date time",
        "timestamp",
        "time",
        "punch time",
        "check time",
        "record time",
        "fichada",
        "fecha hora",
        "attendance time",
    ],
    "punch_date": ["date", "fecha", "work date", "record date"],
    "punch_time": ["time", "hora", "check time", "record time", "attendance time"],
    "event_type": [
        "event type",
        "tipo",
        "tipo de evento",
        "status",
        "state",
        "verify mode",
        "device name",
    ],
}
